module

public import Mathlib.Algebra.Central.Basic
public import Mathlib.LinearAlgebra.Basis.VectorSpace
public import Mathlib.LinearAlgebra.TensorProduct.Basis
public import Mathlib.LinearAlgebra.TensorProduct.RightExactness
public import Mathlib.RingTheory.Flat.FaithfullyFlat.Basic
public import Mathlib.RingTheory.SimpleRing.Congr
public import BrauerGroup.RingTheory.TwoSidedIdeal.Operations
public import BrauerGroup.RingTheory.TwoSidedIdeal.SpanAsSum

/-!
# Tensor product of simple algebras over a field

In this file, we show that the tensor product of a simple algebra and a central simple algebra is
simple, which in particular implies that the tensor product of two central simple algebras is
another central simple algebra. This is a prerequisite for defining the group law on the Brauer
group.

## Main Results

* `TwoSidedIdeal.map_comap_includeRight`: if `A` is a central simple `K`-algebra, then every
  two-sided ideal of `A ⊗[K] B` is generated by its intersection with `1 ⊗ B`.
* `TwoSidedIdeal.orderIsoMapIncludeRight`: if `A` is a central simple `K`-algebra, then
  `J ↦ J.map includeRight` is an order isomorphism between the two-sided ideals of `B` and the
  two-sided ideals of `A ⊗[K] B`.
* `Algebra.TensorProduct.isSimpleRing`: the tensor product of a central simple algebra and a
  simple algebra is simple.

## References

* [StackProject 074B](https://stacks.math.columbia.edu/tag/074B)

## Tags
Noncommutative algebra, tensor product, simple algebra, central simple algebra

-/

@[expose] public section

open TensorProduct Algebra.TensorProduct

variable {K A B : Type*} [Field K] [Ring A] [Algebra K A] [Ring B] [Algebra K B]

namespace TwoSidedIdeal

private lemma exists_one_tmul_add_sum_tmul_mem [IsSimpleRing A] {I : TwoSidedIdeal (A ⊗[K] B)}
    {a₀ : A} (ha₀ : a₀ ≠ 0) {b₀ : B} {ι : Type*} {s : Finset ι} {a : ι → A} {b : ι → B}
    (h : a₀ ⊗ₜ[K] b₀ + ∑ x ∈ s, a x ⊗ₜ[K] b x ∈ I) :
    ∃ a' : ι → A, (1 : A) ⊗ₜ[K] b₀ + ∑ x ∈ s, a' x ⊗ₜ[K] b x ∈ I := by
  obtain ⟨n, xL, xR, heq⟩ := IsSimpleRing.exists_sum_mul_mul_eq_one ha₀
  have key : (1 : A) ⊗ₜ[K] b₀ + ∑ x ∈ s, (∑ i, xL i * a x * xR i) ⊗ₜ[K] b x
      = ∑ i, xL i ⊗ₜ (1 : B) * (a₀ ⊗ₜ[K] b₀ + ∑ x ∈ s, a x ⊗ₜ[K] b x) * xR i ⊗ₜ (1 : B) := by
    simp only [mul_add, tmul_mul_tmul, one_mul, Finset.mul_sum, add_mul, mul_one,
      Finset.sum_mul, Finset.sum_add_distrib]
    rw [← sum_tmul, heq, Finset.sum_comm]
    simp_rw [← sum_tmul]
  exact ⟨fun x ↦ ∑ i, xL i * a x * xR i, key ▸ sum_mem fun i _ ↦
    I.mul_mem_right _ _ (I.mul_mem_left _ _ h)⟩

private lemma sum_commutator_tmul_mem {I : TwoSidedIdeal (A ⊗[K] B)} {b₀ : B} {ι : Type*}
    {s : Finset ι} {a : ι → A} {b : ι → B}
    (h : (1 : A) ⊗ₜ[K] b₀ + ∑ x ∈ s, a x ⊗ₜ[K] b x ∈ I) (z : A) :
    ∑ x ∈ s, (z * a x - a x * z) ⊗ₜ[K] b x ∈ I := by
  have mem := I.sub_mem (I.mul_mem_left (z ⊗ₜ 1) _ h) (I.mul_mem_right _ (z ⊗ₜ 1) h)
  convert mem using 2
  simp [mul_add, add_mul, Finset.mul_sum, Finset.sum_mul, tmul_mul_tmul,
    ← Finset.sum_sub_distrib, ← sub_tmul]

private lemma eq_zero_of_one_tmul_add_sum_algebraMap_tmul_mem {I : TwoSidedIdeal (A ⊗[K] B)}
    (hI : I.comap (includeRight : B →ₐ[K] A ⊗[K] B) = ⊥) {b₀ : B} {ι : Type*} {s : Finset ι}
    {c : ι → K} {b : ι → B}
    (h : (1 : A) ⊗ₜ[K] b₀ + ∑ x ∈ s, algebraMap K A (c x) ⊗ₜ[K] b x ∈ I) :
    b₀ + ∑ x ∈ s, c x • b x = 0 := by
  rw [← mem_bot B, ← hI, mem_comap]
  simpa only [map_add, map_sum, includeRight_apply, tmul_smul, smul_tmul',
    ← Algebra.algebraMap_eq_smul_one] using h

variable [IsSimpleRing A] [hA : Algebra.IsCentral K A]

/-- Let `A` be a central simple `K`-algebra. If a two-sided ideal `I` of `A ⊗[K] B` intersects
`1 ⊗ B` trivially, then any element `∑ i ∈ s, a i ⊗ₜ b i` of `I` with the `b i` linearly
independent has all coefficients `a i` equal to zero. -/
lemma eq_zero_of_sum_tmul_mem {I : TwoSidedIdeal (A ⊗[K] B)}
    (hI : I.comap (includeRight : B →ₐ[K] A ⊗[K] B) = ⊥)
    {ι : Type*} {b : ι → B} (hb : LinearIndependent K b) {s : Finset ι} {a : ι → A}
    (h : ∑ i ∈ s, a i ⊗ₜ[K] b i ∈ I) : ∀ i ∈ s, a i = 0 := by
  classical
  induction s using Finset.induction_on generalizing a with
  | empty => simp
  | insert j s hjs ih =>
    rw [Finset.sum_insert hjs] at h
    rcases eq_or_ne (a j) 0 with hj | hj
    · simp_all
    obtain ⟨a', ha'⟩ := exists_one_tmul_add_sum_tmul_mem hj h
    have hcen (x : ι) : ∃ c : K, x ∈ s → a' x = algebraMap K A c := by
      by_cases hx : x ∈ s
      · obtain ⟨c, hc⟩ := (hA.mem_center_iff K).1 <| Subalgebra.mem_center_iff.2
          fun z ↦ sub_eq_zero.1 <| ih (a := fun x ↦ z * a' x - a' x * z)
            (sum_commutator_tmul_mem ha' z) x hx
        exact ⟨c, fun _ ↦ hc⟩
      · exact ⟨0, fun h ↦ absurd h hx⟩
    choose c hc using hcen
    have h0 : b j + ∑ x ∈ s, c x • b x = 0 := by
      refine eq_zero_of_one_tmul_add_sum_algebraMap_tmul_mem hI ?_
      rwa [show (∑ x ∈ s, algebraMap K A (c x) ⊗ₜ[K] b x) = ∑ x ∈ s, a' x ⊗ₜ[K] b x from
        Finset.sum_congr rfl fun x hx ↦ by rw [hc x hx]]
    refine absurd ?_ (hb.notMem_span_image (show j ∉ (↑s : Set ι) by simpa using hjs))
    rw [eq_neg_of_add_eq_zero_left h0]
    exact Submodule.neg_mem _ <| Submodule.sum_mem _ fun x hx ↦ Submodule.smul_mem _ _ <|
      Submodule.subset_span <| Set.mem_image_of_mem b (by simpa using hx)

/-- If `A` is a central simple `K`-algebra, then a two-sided ideal of `A ⊗[K] B` intersecting
`1 ⊗ B` trivially is trivial. -/
lemma eq_bot_of_comap_includeRight_eq_bot (I : TwoSidedIdeal (A ⊗[K] B))
    (hI : I.comap (includeRight : B →ₐ[K] A ⊗[K] B) = ⊥) : I = ⊥ := by
  obtain ⟨ι, 𝓑⟩ := Module.Free.exists_basis K B
  refine _root_.eq_bot_iff.mpr fun x hx ↦ ?_
  obtain ⟨r, rfl⟩ := TensorProduct.eq_repr_basis_right 𝓑 x
  simp only [Finsupp.sum] at hx ⊢
  simp [Finset.eq_empty_of_forall_notMem fun i hi ↦ Finsupp.mem_support_iff.1 hi <|
    eq_zero_of_sum_tmul_mem hI 𝓑.linearIndependent hx i hi]

/-- Let `A` be a central simple `K`-algebra and `B` any `K`-algebra. Then every two-sided ideal
of `A ⊗[K] B` is generated by its intersection with `1 ⊗ B`.

This is a slightly different version of the statement in the stacks project, where `K` (which is
a central division algebra there) is generalized to a central simple algebra, and `W` (a two-sided
sub-vector space there) is specialized to a two-sided ideal of `A ⊗ B`. -/
@[stacks 074B]
lemma map_comap_includeRight (I : TwoSidedIdeal (A ⊗[K] B)) :
    (I.comap (includeRight : B →ₐ[K] A ⊗[K] B)).map includeRight = I := by
  refine le_antisymm ((map_le_iff_le_comap _ _).2 le_rfl) ?_
  set J := (I.comap (includeRight : B →ₐ[K] A ⊗[K] B)).asIdeal with hJ
  set g : A ⊗[K] B →ₐ[K] A ⊗[K] (B ⧸ J) := lTensor A (Ideal.Quotient.mkₐ K J) with hg
  have hsurj : Function.Surjective g :=
    TensorProduct.map_surjective Function.surjective_id Ideal.Quotient.mk_surjective
  have hker : RingHom.ker g = J.map (includeRight : B →ₐ[K] A ⊗[K] B) := by
    rw [hg, Algebra.TensorProduct.lTensor_ker _ Ideal.Quotient.mk_surjective, AlgHom.ker_coe,
      Ideal.Quotient.mkₐ_ker]
  have hle : RingHom.ker g ≤ I.asIdeal := by
    rw [hker, Ideal.map_le_iff_le_comap, hJ, asIdeal_comap]
  have hcomap : (I.map g).comap (includeRight : B ⧸ J →ₐ[K] A ⊗[K] (B ⧸ J)) = ⊥ := by
    refine _root_.eq_bot_iff.2 fun x hx ↦ ?_
    obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective x
    rw [mem_comap] at hx
    have h1y : (1 : A) ⊗ₜ[K] y ∈ I :=
      (mem_map_iff_of_surjective hsurj hle).1 (by simpa [g] using hx)
    exact (mem_bot _).2 <| Ideal.Quotient.eq_zero_iff_mem.2 <| (mem_comap _).2 h1y
  have hbot := (map_eq_bot_iff_le_ker (f := g) I).1 <|
    eq_bot_of_comap_includeRight_eq_bot (I.map g) hcomap
  refine hbot.trans (Ideal.toTwoSided_le_iff.2 ?_)
  rw [hker, hJ]
  exact map_le_twoSided _

omit [IsSimpleRing A] hA in
/-- Let `A` be a nontrivial `K`-algebra. Mapping a two-sided ideal of `B` into `A ⊗[K] B` and
intersecting back with `1 ⊗ B` recovers the original ideal. -/
lemma comap_map_includeRight [Nontrivial A] (J : TwoSidedIdeal B) :
    (J.map (includeRight : B →ₐ[K] A ⊗[K] B)).comap includeRight = J := by
  refine le_antisymm (fun b hb ↦ ?_) ((map_le_iff_le_comap _ _).1 le_rfl)
  have hle : J.map (includeRight : B →ₐ[K] A ⊗[K] B) ≤ (RingHom.ker
    (lTensor (S := K) A (Ideal.Quotient.mkₐ K J.asIdeal))).toTwoSided :=
    (map_le_iff_le_comap _ _).2 fun x hx ↦ (mem_comap _).2 <| Ideal.mem_toTwoSided.2 <| by
      simp [RingHom.mem_ker, Ideal.Quotient.eq_zero_iff_mem.2 (mem_asIdeal.2 hx)]
  have h0 : (includeRight : (B ⧸ J.asIdeal) →ₐ[K] A ⊗[K] (B ⧸ J.asIdeal))
      (Ideal.Quotient.mk J.asIdeal b) = 0 :=
    RingHom.mem_ker.1 <| Ideal.mem_toTwoSided.1 <| by simpa using hle <| (mem_comap _).1 hb
  exact mem_asIdeal.1 <| Ideal.Quotient.eq_zero_iff_mem.1 <| includeRight_injective
    (algebraMap K A).injective (h0.trans (map_zero _).symm)

/-- This is a generalized version of stacks 074C part 1. -/
@[stacks 074C "part 1"]
def orderIsoMapIncludeRight : TwoSidedIdeal B ≃o TwoSidedIdeal (A ⊗[K] B) where
  toFun J := J.map includeRight
  invFun I := I.comap includeRight
  left_inv := comap_map_includeRight
  right_inv := map_comap_includeRight
  map_rel_iff' {J J'} := ⟨fun h ↦ by rwa [Equiv.coe_fn_mk, map_le_iff_le_comap,
    comap_map_includeRight] at h, map_mono _⟩

end TwoSidedIdeal

/-- The tensor product of a central simple algebra and a simple algebra is simple.
This is slightly more general than the statement in the stacks project, which requires `A` to be
a skew field rather than merely a simple ring. -/
@[stacks 074C "part 2"]
instance Algebra.TensorProduct.isSimpleRing [IsSimpleRing A] [Algebra.IsCentral K A]
    [IsSimpleRing B] : IsSimpleRing (A ⊗[K] B) := by
  refine ⟨⟨fun I ↦ ?_⟩⟩
  rcases eq_bot_or_eq_top (I.comap (includeRight : B →ₐ[K] A ⊗[K] B)) with h | h <;>
    rw [← I.map_comap_includeRight, h]
  · exact Or.inl TwoSidedIdeal.map_bot
  · exact Or.inr <| TwoSidedIdeal.eq_top _ <|
      map_one (includeRight : B →ₐ[K] A ⊗[K] B) ▸ TwoSidedIdeal.mem_map_of_mem
        (f := (includeRight : B →ₐ[K] A ⊗[K] B)) (TwoSidedIdeal.mem_top B (x := 1))

instance Algebra.TensorProduct.isSimpleRing' [IsSimpleRing B] [Algebra.IsCentral K B]
    [IsSimpleRing A] : IsSimpleRing (A ⊗[K] B) :=
  IsSimpleRing.of_ringEquiv (Algebra.TensorProduct.comm K B A).toRingEquiv <|
    Algebra.TensorProduct.isSimpleRing (K := K) (A := B) (B := A)
