module

public import Mathlib.Data.ZMod.QuotientGroup
public import Mathlib.Topology.Instances.AddCircle.Defs

/-!
# The additive circle over `ℚ`

The rational circle `RatAddCircle := AddCircle (1 : ℚ)` is the torsion group `ℚ ⧸ ℤ`. This
file mimics the `ZMod`-API of `Mathlib.Topology.Instances.AddCircle.Real` for the rational
circle, and assembles its torsion structure:

* `ZMod.toRatAddCircle : ZMod N →+ RatAddCircle`, injective, with image the cyclic subgroup
  `RatAddCircle.cyclic N` generated by `1/N` (`ZMod.toRatAddCircle_range`);
* `RatAddCircle.cyclic_le` : `cyclic m ≤ cyclic n` for `m ∣ n`, `n ≠ 0`, whence the family
  is directed (`RatAddCircle.directed_cyclic`);
* `RatAddCircle.iSup_cyclic` : `⨆ N, cyclic N = ⊤` — every element of `ℚ ⧸ ℤ` lies in the
  cyclic subgroup indexed by its denominator;
* `ZMod.toRatAddCircleEquiv : ZMod N ≃+ cyclic N` and
  `RatAddCircle.iSupCyclicEquiv : (⨆ N, cyclic N) ≃+ RatAddCircle`.

This is the target-side substrate for assembling `Br K ≃ ℚ/ℤ` from the relative Brauer
groups of the unramified tower as a directed union, with no colimit machinery.
-/

@[expose] public section

noncomputable section

open AddSubgroup

/-- The rational circle `ℚ ⧸ ℤ`. -/
abbrev RatAddCircle := AddCircle (1 : ℚ)

namespace ZMod

variable {N : ℕ} [NeZero N]

/-- The `AddMonoidHom` from `ZMod N` to `ℚ ⧸ ℤ` sending `j mod N` to `j / N mod 1`. -/
def toRatAddCircle : ZMod N →+ RatAddCircle :=
  lift N ⟨AddMonoidHom.mk' (fun j ↦ ↑(j / N : ℚ)) (by simp [add_div]),
    by simp [div_self (NeZero.ne (N : ℚ))]⟩

lemma toRatAddCircle_intCast (j : ℤ) :
    toRatAddCircle (j : ZMod N) = ↑(j / N : ℚ) := by
  simp [toRatAddCircle]

lemma toRatAddCircle_natCast (j : ℕ) :
    toRatAddCircle (j : ZMod N) = ↑(j / N : ℚ) := by
  simpa using toRatAddCircle_intCast (N := N) j

/-- Explicit formula for `toRatAddCircle j`. Note that this is "evil" because it uses
`ZMod.val`. Where possible, it is recommended to lift `j` to `ℤ` and use
`toRatAddCircle_intCast` instead. -/
lemma toRatAddCircle_apply (j : ZMod N) :
    toRatAddCircle j = ↑(j.val / N : ℚ) := by
  rw [← toRatAddCircle_natCast, natCast_zmod_val]

variable (N) in
lemma toRatAddCircle_injective : Function.Injective (toRatAddCircle : ZMod N → _) := by
  intro x y hxy
  have : (0 : ℚ) < N := Nat.cast_pos.mpr (NeZero.pos _)
  rwa [toRatAddCircle_apply, toRatAddCircle_apply, AddCircle.coe_eq_coe_iff_of_mem_Ico,
    div_left_inj' this.ne', Nat.cast_inj, (val_injective N).eq_iff] at hxy <;>
  exact ⟨by positivity, by simpa only [zero_add, div_lt_one this, Nat.cast_lt] using val_lt _⟩

@[simp] lemma toRatAddCircle_inj {j k : ZMod N} :
    toRatAddCircle j = toRatAddCircle k ↔ j = k :=
  (toRatAddCircle_injective N).eq_iff

@[simp] lemma toRatAddCircle_eq_zero {j : ZMod N} : toRatAddCircle j = 0 ↔ j = 0 :=
  map_eq_zero_iff _ (toRatAddCircle_injective N)

end ZMod

namespace RatAddCircle

/-- The cyclic subgroup of `ℚ ⧸ ℤ` generated by `1 / N`; for `N = 0` it is trivial. -/
def cyclic (N : ℕ) : AddSubgroup RatAddCircle :=
  zmultiples (↑((N : ℚ)⁻¹) : RatAddCircle)

@[simp] lemma cyclic_zero : cyclic 0 = ⊥ := by
  simp [cyclic]

end RatAddCircle

variable {N : ℕ} [NeZero N] in
lemma ZMod.toRatAddCircle_intCast_eq_zsmul (k : ℤ) :
    toRatAddCircle (k : ZMod N) = k • (↑((N : ℚ)⁻¹) : RatAddCircle) := by
  have hq : (k / N : ℚ) = k • ((N : ℚ))⁻¹ := by rw [zsmul_eq_mul, div_eq_mul_inv]
  rw [toRatAddCircle_intCast, hq, QuotientAddGroup.mk_zsmul]

variable {N : ℕ} [NeZero N] in
lemma ZMod.toRatAddCircle_range :
    (toRatAddCircle (N := N)).range = RatAddCircle.cyclic N := by
  apply le_antisymm
  · rintro - ⟨j, rfl⟩
    obtain ⟨k, rfl⟩ := ZMod.intCast_surjective j
    exact ⟨k, (toRatAddCircle_intCast_eq_zsmul k).symm⟩
  · rintro - ⟨k, rfl⟩
    exact ⟨(k : ZMod N), toRatAddCircle_intCast_eq_zsmul k⟩

namespace RatAddCircle

lemma cyclic_le {m n : ℕ} (h : m ∣ n) (hn : n ≠ 0) : cyclic m ≤ cyclic n := by
  rcases eq_or_ne m 0 with rfl | hm
  · simp
  obtain ⟨k, rfl⟩ := h
  have hk : (k : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr fun h0 ↦ hn (by simp [h0])
  rw [cyclic, cyclic, zmultiples_le]
  refine ⟨k, ?_⟩
  have hq : (((m : ℚ))⁻¹ : ℚ) = (k : ℤ) • (((m * k : ℕ) : ℚ))⁻¹ := by
    rw [zsmul_eq_mul]
    push_cast
    rw [mul_inv, mul_comm ((m : ℚ))⁻¹, ← mul_assoc, mul_inv_cancel₀ hk, one_mul]
  conv_rhs => rw [hq, QuotientAddGroup.mk_zsmul]

lemma directed_cyclic : Directed (· ≤ ·) cyclic := by
  intro a b
  rcases eq_or_ne a 0 with rfl | ha
  · exact ⟨b, by simp, le_rfl⟩
  rcases eq_or_ne b 0 with rfl | hb
  · exact ⟨a, le_rfl, by simp⟩
  exact ⟨a * b, cyclic_le (dvd_mul_right a b) (mul_ne_zero ha hb),
    cyclic_le (dvd_mul_left b a) (mul_ne_zero ha hb)⟩

/-- Every element of `ℚ ⧸ ℤ` is torsion: it lies in the cyclic subgroup indexed by its
denominator, so the cyclic subgroups exhaust the rational circle. -/
lemma iSup_cyclic : ⨆ N, cyclic N = ⊤ := by
  rw [eq_top_iff]
  rintro x -
  induction x using QuotientAddGroup.induction_on with | H q =>
  refine le_iSup cyclic q.den ⟨q.num, ?_⟩
  have hq : (q : ℚ) = q.num • ((q.den : ℚ))⁻¹ := by
    rw [zsmul_eq_mul, ← div_eq_mul_inv, Rat.num_div_den]
  conv_rhs => rw [hq, QuotientAddGroup.mk_zsmul]

/-- `ZMod N` is isomorphic to the cyclic subgroup of `ℚ ⧸ ℤ` generated by `1/N`. -/
def _root_.ZMod.toRatAddCircleEquiv (N : ℕ) [NeZero N] : ZMod N ≃+ cyclic N :=
  (AddMonoidHom.ofInjective (ZMod.toRatAddCircle_injective N)).trans
    (AddEquiv.addSubgroupCongr ZMod.toRatAddCircle_range)

/-- The rational circle `ℚ ⧸ ℤ` is the union of its cyclic subgroups: the directed
supremum `⨆ N, cyclic N` is all of `RatAddCircle`. -/
def iSupCyclicEquiv : (⨆ N, cyclic N : AddSubgroup RatAddCircle) ≃+ RatAddCircle :=
  (AddEquiv.addSubgroupCongr iSup_cyclic).trans AddSubgroup.topEquiv

end RatAddCircle
