module

public import BrauerGroup.Algebra.CrossProduct.CentralSimple
public import BrauerGroup.GroupTheory.CyclicIndex

/-!
# Cyclic algebras as crossed products

For a finite Galois extension `K / F` whose Galois group is generated by `σ`
(`hσ : ∀ τ, τ ∈ Subgroup.zpowers σ`) and a unit `a : Fˣ`, the cyclic algebra `(K/F, σ, a)` is
the crossed product of the *carry cocycle*

  `cyclicCocycle σ hσ a (σ^i, σ^j) = a ^ carry i j`,

where `carry i j ∈ {0, 1}` records the overflow of `i + j` in `ZMod (orderOf σ)`. All central
simple structure (ring, `F`-algebra, `IsCentral`, `IsSimpleRing`, dimension `[K:F]²`) is
inherited from `CrossProductAlgebra` for free.

The classical presentation `K⟨u⟩` with `u * c = σ(c) * u` and `u ^ n = a` is recovered by
`u := of _ σ` via the spec lemmas `of_pow_eq_of` and `of_pow_orderOf` — there is no second
construction to compare against.
-/

@[expose] public section

open groupCohomology Subgroup

suppress_compilation

variable {F K : Type*} [Field F] [Field K] [Algebra F K] [FiniteDimensional F K]
variable (σ : Gal(K/F)) (hσ : ∀ τ, τ ∈ Subgroup.zpowers σ) (a : Fˣ)

/-- The carry cocycle of the cyclic algebra `(K/F, σ, a)`: at `(σ^i, σ^j)` it is
`a ^ carry i j`, viewed in `Kˣ`. -/
def cyclicCocycle : Gal(K/F) × Gal(K/F) → Kˣ :=
  fun p ↦ Units.map (algebraMap F K) a ^ ZMod.carry (genExp σ hσ p.1) (genExp σ hσ p.2)

omit [FiniteDimensional F K] in
lemma cyclicCocycle_apply (τ₁ τ₂ : Gal(K/F)) :
    cyclicCocycle σ hσ a (τ₁, τ₂) =
      Units.map (algebraMap F K) a ^ ZMod.carry (genExp σ hσ τ₁) (genExp σ hσ τ₂) := rfl

omit [FiniteDimensional F K] in
@[simp] lemma cyclicCocycle_one_left (τ : Gal(K/F)) : cyclicCocycle σ hσ a (1, τ) = 1 := by
  simp [cyclicCocycle_apply]

omit [FiniteDimensional F K] in
@[simp] lemma cyclicCocycle_one_right (τ : Gal(K/F)) : cyclicCocycle σ hσ a (τ, 1) = 1 := by
  simp [cyclicCocycle_apply]

omit [FiniteDimensional F K] in
/-- Units coming from the base field are Galois-fixed. -/
lemma smul_units_map_algebraMap (τ : Gal(K/F)) (b : Fˣ) :
    τ • (Units.map (algebraMap F K) b : Kˣ) = Units.map (algebraMap F K) b := by
  ext
  simp [AlgEquiv.smul_units_def, AlgEquiv.commutes]

/-- The carry cocycle is a 2-cocycle: the cocycle identity is carry arithmetic, since the
coefficient `a` is Galois-fixed. -/
instance : Fact (IsMulCocycle₂ (cyclicCocycle σ hσ a)) where
  out g h j := by
    have key : ∀ (τ : Gal(K/F)) (c : ℤ),
        τ • ((Units.map (algebraMap F K) a : Kˣ) ^ c)
          = (Units.map (algebraMap F K) a : Kˣ) ^ c := fun τ c ↦ by
      rw [← MulDistribMulAction.toMonoidHom_apply, map_zpow,
        MulDistribMulAction.toMonoidHom_apply, smul_units_map_algebraMap]
    simp only [cyclicCocycle_apply, genExp_mul, key, ← zpow_add]
    congr 1
    exact ZMod.carry_cocycle _ _ _

/-- The cyclic algebra `(K/F, σ, a)`: the crossed product of the carry cocycle. Ring,
`F`-algebra, central simple structure and `dim = [K:F]²` are inherited from
`CrossProductAlgebra`. -/
abbrev CyclicAlgebra := CrossProductAlgebra (cyclicCocycle σ hσ a)

namespace CyclicAlgebra

open CrossProductAlgebra

/-- Below the order of `σ`, powers of the canonical unit `of _ σ` are the canonical units of
the powers of `σ` — no carry appears. -/
lemma of_pow_eq_of : ∀ i : ℕ, i < orderOf σ →
    of (cyclicCocycle σ hσ a) σ ^ i = of (cyclicCocycle σ hσ a) (σ ^ i)
  | 0, _ => Units.ext <| by
    rw [pow_zero, pow_zero, of_one, cyclicCocycle_one_left]
    simp
  | (i + 1), hi => Units.ext <| by
    haveI : NeZero (orderOf σ) := ⟨(orderOf_pos σ).ne'⟩
    have h1 : 1 < orderOf σ := lt_of_le_of_lt (Nat.le_add_left 1 i) hi
    have hgen : genExp σ hσ σ = (1 : ZMod (orderOf σ)) := by simpa using genExp_pow σ hσ 1
    have hcocy : cyclicCocycle σ hσ a (σ ^ i, σ) = 1 := by
      rw [cyclicCocycle_apply, genExp_pow, hgen, ZMod.carry_eq_ite,
        ZMod.val_one'' (by omega), ZMod.val_natCast, Nat.mod_eq_of_lt (by omega),
        if_neg (by omega), zpow_zero]
    rw [pow_succ, of_pow_eq_of i (lt_trans (Nat.lt_succ_self i) hi), Units.val_mul,
      of_mul_of, ← pow_succ, hcocy]
    simp

/-- The presentation relation `u ^ n = a` for the cyclic algebra, `u := of _ σ`,
`n := orderOf σ`. (Fails for `σ = 1`, where the crossed product is the base field.) -/
lemma of_pow_orderOf (hσ1 : σ ≠ 1) :
    (of (cyclicCocycle σ hσ a) σ : CrossProductAlgebra (cyclicCocycle σ hσ a)) ^ orderOf σ
      = incl (cyclicCocycle σ hσ a) (algebraMap F K a) := by
  haveI : NeZero (orderOf σ) := ⟨(orderOf_pos σ).ne'⟩
  have h1 : 1 < orderOf σ := by
    have h0 := orderOf_pos σ
    have hne : orderOf σ ≠ 1 := fun h ↦ hσ1 (orderOf_eq_one_iff.1 h)
    omega
  have hgen : genExp σ hσ σ = (1 : ZMod (orderOf σ)) := by simpa using genExp_pow σ hσ 1
  have hcarry : cyclicCocycle σ hσ a (σ ^ (orderOf σ - 1), σ)
      = Units.map (algebraMap F K) a := by
    rw [cyclicCocycle_apply, genExp_pow, hgen, ZMod.carry_eq_ite,
      ZMod.val_one'' (by omega), ZMod.val_natCast, Nat.mod_eq_of_lt (by omega),
      if_pos (by omega), zpow_one]
  have hn : orderOf σ = (orderOf σ - 1) + 1 := by omega
  rw [← Units.val_pow_eq_pow_val, hn, pow_succ,
    of_pow_eq_of σ hσ a _ (by omega), Units.val_mul, of_mul_of, ← pow_succ, ← hn,
    pow_orderOf_eq_one, hcarry, of_one, cyclicCocycle_one_left]
  simp [Units.coe_map]

omit [FiniteDimensional F K] in
/-- Cocycle-level multiplicativity: carry exponents add. Feeds the class-level
`[(σ,a)]·[(σ,b)] = [(σ,ab)]` once trunk 4.11 lands. -/
lemma cyclicCocycle_mul_cyclicCocycle (b : Fˣ) :
    cyclicCocycle σ hσ a * cyclicCocycle σ hσ b = cyclicCocycle σ hσ (a * b) := by
  funext p
  obtain ⟨τ₁, τ₂⟩ := p
  simp [cyclicCocycle_apply, Pi.mul_apply, map_mul, mul_zpow]

end CyclicAlgebra
